### ISSUE TITLE
New features for the tool

### ISSUE THREAD

**Issue by Spomky** [fido-alliance/conformance-test-tools-resources#566]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/wiki) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 1.0
- [ ] UAF 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.3.4

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

I will be happy to see some feature in the conformance test tool:

* Depending on the selected tests to run, is it possible to see the total number of tests that will be performed?
* Is it possible to run a specific test instead of all of them? This could be very useful when trying to debug a test among others that succeeded.

Thank you.

**Comment by sbweeden** [comment]
To follow on from the idea of running a specific test instead of all of them, the more general case that would be useful is to be able to more easily correlate request payloads to a give test case. I would like to see the server spec include an optional request body element (which the conformance tool should populate) which indicates which test case (and sub-request number for those test cases which use multiple request/responses) is being run. This would help a lot when trolling through server logs. 

Another thing, in my case running the tool on MacOS, when the inspector is opened there is still no ability to export the network trace from the client or use copy/paste. I believe this can be done with a little work, for example this seems useful:
https://pracucci.com/atom-electron-enable-copy-and-paste.html
