### ISSUE TITLE
Forward compatibility in HID P-11

### ISSUE THREAD

**Issue by kaczmarczyck** [fido-alliance/conformance-test-tools-resources#600]
## What protocol are you implementing?

- [x] CTAP2.0
- [x] CTAP2.1

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators

## Issue description

Hi, thanks for creating a new version for CTAP 2.1! This issue is about `hid-1.js` and test P-11 for keepalive. May I suggest to use a different command that requires user presence than GetAssertion without credentials? This allows CTAP 2.1 preview authenticators to still be certified for CTAP 2.0 (like my proposal in #595).

The protocol [step 6.6 for GetAssertion](https://fidoalliance.org/specs/fido-v2.1-rd-20201208/fido-client-to-authenticator-protocol-v2.1-rd-20201208.html#op-getassn-step-locate-credentials) now returns before user presence checks.

**Comment by kaczmarczyck** [comment]
Do you mind reopening? The test seems to be still inconsistent with the specification. I think it requires to do a UP check before responding with `CTAP2_ERR_NO_CREDENTIALS` [1], but in 2.1, this error code is returned ealier [2].

[1] https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/tests/CTAP2/Transports/hid-1.js#L361
[2] https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#sctn-getAssert-authnr-alg

**Comment by iirachek** [comment]
Sure, I'll take a look.

**Comment by iirachek** [comment]
The intent of P-11 test is to ensure the correct processing of `CTAPHID_CANCEL` by authenticator during ongoing request. 
At the same time P-11 test is very similar to [P-10](https://github.com/fido-alliance/ctap2.1-conformance-module/blob/ead4f87b288961173b24f18c7e354a82a11bd640/tests/CTAP2/Transports/hid-1.js#L315), which covers same scenario using `MakeCredential` instead of `GetAssertion`.  Without question, the correct cancelling of both commands is essential for any authenticator.

Since the CTAP2.1 specification of `GetAssertion` algorithm was updated to check UP after asserting available credentials, it cannot be used in a way the testcase intends without going beyond the scope of transport tests. The closest alternative would be [AuthenticatorSelection](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#authenticatorSelection), but this one isn't available for CTAP2.0. 

With handling of `CTAPHID_CANCEL` being covered by P-10, the right call might be to skip/disable P-11 and introduce a new test with `AuthenticatorSelection` command specifically for CTAP2.1 HID.

**Comment by kaczmarczyck** [comment]
Thanks for checking. I agree this is one plausible solution.

**Comment by iirachek** [comment]
This should be resolved with changes introduced in the 1.17.18 version.
