### ISSUE TITLE
Cannot found authenticationAlgorithm string "secp521r1_ecdsa_sha256_raw"

### ISSUE THREAD

**Issue by stephenWebComm** [fido-alliance/conformance-test-tools-resources#662]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 Server(mds3)

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?
- [x] Server

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.6.41

## What is the OS and the version are you running?

For desktop tools
- [x] OSX

## Issue description
in Virtual Secp521r1 SHA512 FIDO2 Conformance Testing CTAP2 Authenticator.json file
authenticationAlgorithms value -> ["secp521r1_ecdsa_sha256_raw"]
but in https://github.com/fido-alliance/conformance-test-tools-resources/blob/master/snippets/registry.js
cannot found this value.

**Comment by herrjemand** [comment]
Addressed in 1.6.46

**Comment by ynojima** [comment]
@herrjemand,
Allow me to double-check, [fido-registry-v2.1-ps-20191217.html](https://fidoalliance.org/specs/fido-common-specs-v2.1-ps-20191217/fido-registry-v2.1-ps-20191217.html) defines AuthenticationAlgorithm(0x11) as "secp**512**r1_ecdsa_sha256_raw", but FIDO conformance test tools v1.4.46 returns "secp**521**r1_ecdsa_sha256_raw".
Since "secp521r1" is the correct named curve name, I assume  "secp**512**r1_ecdsa_sha256_raw" is the correct name, and the fido-registry is already corrected in the private repository but not published. Is my understanding right?

**Comment by ynojima** [comment]
Please ignore my previous comment, I found it was fixed in [fido-registry-v2.2-rd-20210525.html](https://fidoalliance.org/specs/common-specs/fido-registry-v2.2-rd-20210525.html#authentication-algorithms)
